/**
 * Sends the briefing email via Resend.
 *
 * The briefing text (markdown-ish) gets converted to simple HTML
 * for readability in email clients, with a plain-text fallback.
 */
async function sendBriefingEmail(briefing) {
  const resendModule = await import("resend");
  const Resend = resendModule.Resend || resendModule.default?.Resend;
  const resend = new Resend(process.env.RESEND_API_KEY);

  const today = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  const htmlBody = briefingToHtml(briefing);

  await resend.emails.send({
    from: process.env.EMAIL_FROM || "Portfolio Briefing <briefing@resend.dev>",
    to: process.env.BRIEFING_EMAIL || "",
    subject: `Portfolio Briefing — ${today}`,
    html: htmlBody,
    text: briefing,
  });
}

/**
 * Minimal markdown-to-HTML for email rendering.
 * Handles headers, bold, line breaks. Nothing fancy.
 */
function briefingToHtml(text) {
  const lines = text.split("\n");
  const htmlLines = [];

  htmlLines.push(`
    <div style="font-family: 'Georgia', serif; max-width: 640px; margin: 0 auto; padding: 24px; color: #1a1a1a; line-height: 1.6;">
    <h1 style="font-size: 22px; font-weight: 600; color: #111; border-bottom: 2px solid #c9a84c; padding-bottom: 8px; margin-bottom: 20px;">
      Portfolio Briefing
    </h1>
  `);

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      htmlLines.push("<br>");
      continue;
    }

    if (/^\d+\.\s+[A-Z]/.test(trimmed)) {
      const headerText = trimmed.replace(/^\d+\.\s+/, "");
      htmlLines.push(
        `<h2 style="font-size: 16px; font-weight: 700; color: #c9a84c; margin-top: 24px; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;">${headerText}</h2>`
      );
      continue;
    }

    if (/^[A-Z\s]{4,}$/.test(trimmed) && !trimmed.includes("  ")) {
      htmlLines.push(
        `<h2 style="font-size: 16px; font-weight: 700; color: #c9a84c; margin-top: 24px; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;">${trimmed}</h2>`
      );
      continue;
    }

    const withBold = trimmed.replace(
      /\*\*(.+?)\*\*/g,
      '<strong style="color: #111;">$1</strong>'
    );

    const withTickers = withBold.replace(
      /\b([A-Z]{2,5})\b(?=\s|,|\.|:|;|\))/g,
      (match) => {
        const skipWords = new Set([
          "THE", "AND", "FOR", "BUT", "NOT", "ALL", "ARE", "WAS",
          "HAS", "HAD", "ITS", "NEW", "LOW", "HIGH", "THIS", "THAT",
          "WITH", "FROM", "WEEK", "LAST", "NEXT", "THAN",
        ]);
        if (skipWords.has(match)) return match;
        return `<span style="color: #b8860b; font-weight: 600;">${match}</span>`;
      }
    );

    htmlLines.push(`<p style="margin: 4px 0;">${withTickers}</p>`);
  }

  htmlLines.push(`
    <hr style="border: none; border-top: 1px solid #ddd; margin-top: 32px;">
    <p style="font-size: 12px; color: #999; margin-top: 8px;">
      Generated by Portfolio Briefing Agent · Data from Yahoo Finance · Analysis by Claude
    </p>
    </div>
  `);

  return htmlLines.join("\n");
}

module.exports = { sendBriefingEmail };
